<?php if(!defined('__TYPECHO_ADMIN__')) exit; ?>
<?php
$editorConfig = [
    'placeholder' => _t('开始写作，记录此刻的想法...'),
    'labels' => [
        'editor' => _t('正文编辑器'),
        'blockType' => _t('段落类型'),
        'paragraph' => _t('正文'),
        'heading1' => _t('一级标题'),
        'heading2' => _t('二级标题'),
        'heading3' => _t('三级标题'),
        'heading4' => _t('四级标题'),
        'heading5' => _t('五级标题'),
        'heading6' => _t('六级标题'),
        'bold' => _t('加粗'),
        'italic' => _t('斜体'),
        'underline' => _t('下划线'),
        'strike' => _t('删除线'),
        'code' => _t('行内代码'),
        'subscript' => _t('下标'),
        'superscript' => _t('上标'),
        'link' => _t('链接'),
        'imageUpload' => _t('上传图片'),
        'imageUploadHint' => _t('点击上传或拖拽图片到这里'),
        'imageUploadLimit' => _t('支持图片文件，会自动插入到正文'),
        'uploadingImages' => _t('正在上传 {count} 张图片'),
        'processingImages' => _t('正在处理图片'),
        'clearAll' => _t('清除全部'),
        'cancelUpload' => _t('取消上传'),
        'uploadFailed' => _t('失败'),
        'highlight' => _t('高亮'),
        'textColor' => _t('文字颜色'),
        'clearColor' => _t('清除颜色'),
        'highlightYellow' => _t('黄色高亮'),
        'highlightGreen' => _t('绿色高亮'),
        'highlightBlue' => _t('蓝色高亮'),
        'highlightPink' => _t('粉色高亮'),
        'colorDefault' => _t('默认颜色'),
        'colorRed' => _t('红色'),
        'colorGreen' => _t('绿色'),
        'colorBlue' => _t('蓝色'),
        'colorPurple' => _t('紫色'),
        'colorBrown' => _t('棕色'),
        'bulletList' => _t('无序列表'),
        'orderedList' => _t('有序列表'),
        'taskList' => _t('任务列表'),
        'listType' => _t('列表类型'),
        'scriptType' => _t('上下标'),
        'textAlign' => _t('对齐方式'),
        'alignLeft' => _t('左对齐'),
        'alignCenter' => _t('居中对齐'),
        'alignRight' => _t('右对齐'),
        'alignJustify' => _t('两端对齐'),
        'blockquote' => _t('引用'),
        'codeBlock' => _t('代码块'),
        'horizontalRule' => _t('分割线'),
        'moreBreak' => _t('摘要分割线'),
        'resetFormatting' => _t('清除格式'),
        'undo' => _t('撤销'),
        'redo' => _t('重做'),
        'linkPrompt' => _t('请输入链接地址'),
        'imagePrompt' => _t('请输入图片地址')
    ]
];
?>
<script>
window.TypechoTiptapConfig = <?php echo json_encode($editorConfig, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); ?>;
</script>
<script src="<?php $options->adminStaticUrl('js', 'tiptap-editor.js'); ?>"></script>
