name: Typecho Build Release Ci
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm
        cache-dependency-path: tools/package-lock.json
    - name: Build admin assets
      run: |
        npm ci
        npm run build
      working-directory: tools
    - name: Build
      run: |
        mkdir build
        cp -r LICENSE.txt index.php install.php admin install usr var build/
        mkdir build/usr/uploads/
        chmod 755 build/usr/uploads/
        rm -rf build/admin/src
        rm -rf build/usr/themes/classic-22/static/scss
        cd build && zip -q -r typecho.zip * && mv typecho.zip ../ && cd -
    - name: Upload Release Asset
      uses: shogo82148/actions-upload-release-asset@v1
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./typecho.zip
          asset_name: typecho.zip
          asset_content_type: application/zip
